youtube_api:
  scopes:
    - https://www.googleapis.com/auth/youtube.readonly
    - https://www.googleapis.com/auth/yt-analytics.readonly
    - https://www.googleapis.com/auth/youtube
    - https://www.googleapis.com/auth/youtubepartner
    - https://www.googleapis.com/auth/yt-analytics-monetary.readonly

datastax:
  secure_connect_bundle: "/path/secure_connect_bundle.zip"
  client_id: "your_client_id"
  client_secret: "your_client_secret" 